LONG_PRESS_SEC=10
HOOK_SHORT_PRESS="/etc/ucs/hooks/ucs_hook_short_press.sh"
HOOK_HOLD_2S="/etc/ucs/hooks/ucs_hook_hold_2s.sh"
HOOK_HOLD_5S="/etc/ucs/hooks/ucs_hook_hold_5s.sh"
HOOK_HOLD_10S="/etc/ucs/hooks/ucs_hook_hold_10s.sh"
