# UPM Configuration File
# Target OS: Raspberry Pi OS (Debian/Ubuntu with systemd)

# Configuration: UPM_ENABLE_DEBUG
# Type: boolean
# Range: "true" or "false"
UPM_ENABLE_DEBUG="false"

# Configuration: UPM_LONG_PRESS_SEC
# Type: integer
# Range: 10 to 30 (seconds)
UPM_LONG_PRESS_SEC=10


# Configuration: UPM_BATT_STATE_DEBOUNCE_SEC
# Type: integer
# Range: 1 to 60. Default: 5.
# Description: Delays applying CPU states to prevent thrashing when
# plugging/unplugging.
UPM_BATT_STATE_DEBOUNCE_SEC=5
